version: '3.5'

services:
    mysql:
        image: ubuntu/mysql
        container_name: dockr_mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DOCKR_ASSET_PASSWORD:-password}'
            MYSQL_USER: '${DOCKR_ASSET_USERNAME:-dockr}'
            MYSQL_PASSWORD: '${DOCKR_ASSET_PASSWORD:-password}'
            MYSQL_DATABASE: '${DOCKR_ASSET_DEFAULT_DATABASE:-dockr}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - dockr_mysql:/var/lib/mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-ppassword"]
            retries: 3
            timeout: 5s
        networks:
            - '${DOCKR_NETWORK:-dockr}'

    postgres:
        image: postgres
        container_name: dockr_postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: '${DOCKR_ASSET_USERNAME:-dockr}'
            POSTGRES_PASSWORD: '${DOCKR_ASSET_PASSWORD:-password}'
            POSTGRES_DB: '${DOCKR_ASSET_DEFAULT_DATABASE:-dockr}'
        volumes:
            - dockr_postgres:/var/lib/postgresql/data
        restart: always
        networks:
            - '${DOCKR_NETWORK:-dockr}'

    redis:
        image: 'redis:alpine'
        container_name: dockr_redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - dockr_redis:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        networks:
            - '${DOCKR_NETWORK:-dockr}'

networks:
    dockr:
        external: true

volumes:
    dockr_mysql:
        driver: local
        name: dockr_asset_mysql
    dockr_postgres:
        driver: local
        name: dockr_asset_postgres
    dockr_redis:
        driver: local
        name: dockr_asset_redis
