version: "3.7"
services:
    web:
        image: "${DOCKR_DOCKER_IMAGE}"
        container_name: "${DOCKR_CONTAINER_NAME}-web"
        ports:
            - "${DOCKR_PORT:-80}:80"
        volumes:
            - "${PROJECT_ROOT_DIR}/:/var/www/html"
        networks:
            - "${DOCKR_NETWORK:-dockr}"
        environment:
            DOCKR_COMPOSER_VERSION: "${DOCKR_COMPOSER_VERSION}"
        labels:
            - "TYPE=project"
            - "SERVICE=web"

    worker:
        image: "${DOCKR_DOCKER_IMAGE}"
        container_name: "${DOCKR_CONTAINER_NAME}-worker"
        volumes:
            - "${PROJECT_ROOT_DIR}/:/var/www/html"
        networks:
            - "${DOCKR_NETWORK:-dockr}"
        environment:
            DOCKR_CONTAINER_TYPE: "worker"
            DOCKR_COMPOSER_VERSION: "${DOCKR_COMPOSER_VERSION}"
        labels:
            - "TYPE=project"
            - "SERVICE=worker"

networks:
    dockr:
        external: true
