version: "3.7"
services:
    web:
        image: "${APP_DOCKR_IMAGE}"
        container_name: "${PROJECT_NAME}-web"
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - "${PROJECT_ROOT_DIR}/:/var/www/html"
        networks:
            - '${DOCKR_NETWORK:-dockr}'

networks:
    dockr:
        external: true
