version: "3.7"
services:
    web:
        image: "${DOCKR_DOCKER_IMAGE}"
        container_name: "${DOCKR_CONTAINER_NAME}"
        ports:
            - "${DOCKR_PORT:-80}:80"
        volumes:
            - "${PROJECT_ROOT_DIR}/:/var/www/html"
        networks:
            - '${DOCKR_NETWORK:-dockr}'

networks:
    dockr:
        external: true
