version: "3.7"
services:
    web:
        image: "${DOCKR_DOCKER_IMAGE}"
        container_name: "${DOCKR_CONTAINER_NAME}-web"
        ports:
            - "0:80"
        volumes:
            - "${PROJECT_ROOT_DIR}/:/var/www/html"
            - dockr_composer_cache:/root/.composer/cache
        networks:
            - "${DOCKR_NETWORK:-dockr}"
        environment:
            DOCKR_COMPOSER_VERSION: "${DOCKR_COMPOSER_VERSION}"
        labels:
            - "TYPE=project"
            - "SERVICE=web"
            - "SITE=${DT_SITE:--}"

    worker:
        image: "${DOCKR_DOCKER_IMAGE}"
        container_name: "${DOCKR_CONTAINER_NAME}-worker"
        volumes:
            - "${PROJECT_ROOT_DIR}/:/var/www/html"
        networks:
            - "${DOCKR_NETWORK:-dockr}"
        environment:
            DOCKR_CONTAINER_TYPE: "worker"
            DOCKR_COMPOSER_VERSION: "${DOCKR_COMPOSER_VERSION}"
        labels:
            - "TYPE=project"
            - "SERVICE=worker"
            - "SITE=-"

networks:
    dockr:
        external: true

volumes:
    dockr_composer_cache:
        name: dockr_composer_cache
        external: true
