version: "3.7"
services:
    web:
        image: "${APP_DOCKR_IMAGE}"
        container_name: "${PROJECT_NAME}-web"
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - "${APP_VOLUME_ROOT}:/var/www/html"
        networks:
            - dockr

networks:
    dockr:
        external: true
