ARG DT_PYTHON_TAG

# start by pulling the python image
FROM python:$DT_PYTHON_TAG

ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/opt/.cache

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# copy every content from the local file to the image
COPY ./temp /app

# switch working directory
WORKDIR /app

# install the dependencies and packages in the poetry file
ARG DT_POETRY_VERSION
RUN pip install "poetry==$DT_POETRY_VERSION" && poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi

# Delete the project files from image
RUN rm -rf /app

# configure the container to run in an executed manner
COPY entrypoint.sh /etc/entrypoint.sh
RUN chmod u+x /etc/entrypoint.sh
ENTRYPOINT ["/etc/entrypoint.sh"]
CMD []
