version: '3.5'

services:
    web:
        build:
            context: ${DT_DJANGO_DOCKER_CONTEXT}
            dockerfile: ${DT_DJANGO_DOCKER_FILE}
            args:
                - DT_PYTHON_TAG=${DT_PYTHON_TAG}
                - DT_POETRY_VERSION=${DOCKR_POETRY_VERSION}
                - DT_PROJECT_ROOT_DIR=${PROJECT_ROOT_DIR}
        environment:
#             - DJANGO_APP=${DJANGO_APP}
            - DJANGO_ENV=development
        container_name: "${DOCKR_CONTAINER_NAME}-web"
        networks:
            - "${DOCKR_NETWORK:-dockr}"
        ports:
            - "0:5000"
        volumes:
            - "${PROJECT_ROOT_DIR}/:/app"
        labels:
            - "TYPE=project"
            - "SERVICE=web"
            - "SITE=${DT_SITE:--}"
            - "traefik.http.routers.${DT_TRAEFIK_HOST_KEY}.rule=${DT_TRAEFIK_PROXY_RULE}"
            - "traefik.http.routers.${DT_TRAEFIK_HOST_KEY}.service=${DT_TRAEFIK_HOST_KEY}_service"
            - "traefik.http.services.${DT_TRAEFIK_HOST_KEY}_service.loadbalancer.server.port=80"
            - "traefik.http.routers.${DT_TRAEFIK_HOST_KEY}_secure.tls=true"
            - "traefik.http.routers.${DT_TRAEFIK_HOST_KEY}_secure.rule=${DT_TRAEFIK_PROXY_RULE}"
            - "traefik.http.routers.${DT_TRAEFIK_HOST_KEY}_secure.service=${DT_TRAEFIK_HOST_KEY}_secure_service"
            - "traefik.http.services.${DT_TRAEFIK_HOST_KEY}_secure_service.loadbalancer.server.port=80"

networks:
    dockr:
        external: true
